# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Deploy to Amazon ECS

on:
  push:
    branches: [dev_1, dev_2]                                # containerDefinitions section of your task definition

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    # environment: dev_1


    steps:  
      - name: Determine Secret Suffix
        run: |
          if [ "${{ github.ref }}" == "refs/heads/dev_1" ]; then
            echo "PROJECT=kb" >> $GITHUB_ENV
            echo "SUFFIX=kendriyabhandar" >> $GITHUB_ENV
          else
            echo "PROJECT=nafed" >> $GITHUB_ENV
            echo "SUFFIX=nafed" >> $GITHUB_ENV
          fi

      - name: Set Required ENV
        run: |
            echo "AWS_REGION=ap-south-1" >> $GITHUB_ENV
            echo "ECR_REPOSITORY=${{ env.SUFFIX }}" >> $GITHUB_ENV
            echo "ECS_SERVICE=${{ env.SUFFIX }}-ecs-service" >> $GITHUB_ENV           
            echo "ECS_CLUSTER=${{ env.SUFFIX }}-cluster" >> $GITHUB_ENV             
            echo "CONTAINER_NAME=${{ env.SUFFIX }}-api-container" >> $GITHUB_ENV        
    
      - name: Determine Secret Suffix
        run: |
          if [ "${{ github.ref }}" == "refs/heads/dev_1" ]; then
            echo "SUFFIX=1" >> $GITHUB_ENV
          else
            echo "SUFFIX=2" >> $GITHUB_ENV
          fi

      - name: Print Prefex Variable
        run: echo "${{ env.SUFFIX }} ${{ env.PROJECT }} "  | sed 's/./& /g'   
      
        
      - name: Print ENV Variable
        run: echo "${{ env }}"  | sed 's/./& /g'  

      - name: Print Secret
        run: echo ${{ secrets[format('Name_{0}', env.SUFFIX)] }}  | sed 's/./& /g'   

      - name: Print Variable
        run: echo ${{ vars[format('Name_{0}', env.SUFFIX)] }}  | sed 's/./& /g'   

      - name: ref
        run: echo ${{secrets.NAME}}  | sed 's/./& /g'
      - name: ref
        run: echo ${{secrets.Name}}  | sed 's/./& /g'

      - name: Checkout_1
        if: ${{github.ref == 'refs/heads/dev_1'}}        
        run: echo ${{secrets.NAME}}  | sed 's/./& /g'
        

      - name: Checkout_2
        if: ${{github.ref == 'refs/heads/dev_2' }}            
        run: echo ${{secrets.Name}}
        
      