# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Deploy to Amazon ECS

on:
  push:
    branches: [dev_1, dev_2]                                # containerDefinitions section of your task definition

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: ${{ env.ENV_NAME }}


    steps:  
      - name: Determine Environment Name Based on Branch
        run: |
          if [ "${{ github.ref }}" == "refs/heads/dev_1" ]; then
            echo "ENV_NAME=dev_1" >> $GITHUB_ENV
          else
            echo "ENV_NAME=dev_2" >> $GITHUB_ENV
          fi
        
      - name: Determine Secret Suffix
        run: |
          if [ "${{ github.ref }}" == "refs/heads/dev_1" ]; then
            echo "SUFFIX=_1" >> $GITHUB_ENV
          else
            echo "SUFFIX=_2" >> $GITHUB_ENV
          fi

      - name: Print Prefex Variable
        run: echo "${{ env.SUFFIX }} ${{ env.ENV_NAME }}"  | sed 's/./& /g'   

      - name: Print Secret
        run: echo ${{ secrets[format('Name{0}', env.SUFFIX)] }}  | sed 's/./& /g'   

      - name: Print Variable
        run: echo ${{ vars[format('Name{0}', env.SUFFIX)] }}  | sed 's/./& /g'   

      - name: ref
        run: echo ${{secrets.NAME}}  | sed 's/./& /g'
      - name: ref
        run: echo ${{secrets.Name}}  | sed 's/./& /g'

      - name: Checkout_1
        if: ${{github.ref == 'refs/heads/dev_1'}}        
        run: echo ${{secrets.NAME}}  | sed 's/./& /g'
        id: asdsad
        

      - name: Checkout_2
        if: ${{github.ref == 'refs/heads/dev_2' }}            
        run: echo ${{secrets.Name}}
        
      